title: Zachariah Schwab
email: zachariahsws@gmail.com
description: A personal website for Zachariah Schwab
baseurl: ""
url: "zachariahschwab.com"
theme: Academia-Theme
navigation:
  - title: Home
    url: /
  - title: Essays
    url: /essays
  - title: Documents
    url: /documents

outline_thread: true

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

author: Zachariah Schwab
